"""Add useful_life to Category

Revision ID: 855238d986f8
Revises: 8b47101f68e7
Create Date: 2025-06-16 20:00:19.672029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855238d986f8'
down_revision = '8b47101f68e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('useful_life', sa.Integer(), nullable=False, server_default='36'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('useful_life')

    # ### end Alembic commands ###
